from dydx3.constants import API_HOST_SEPOLIA, API_HOST_MAINNET
from decouple import config

TOKEN_FACTOR_10 = ["XLM-USD","DOGE-USD","TRON-USD"]

# !!!! SELECT MODE !!!!
MODE = "DEVELOPMENT"

# Close all open positions and orders
ABORT_ALL_POSITIONS = True

# Find Cointegrated Pairs
FIND_COINTEGRATED = True

# Manage Exits
MANAGE_EXITS = True

# Place Trades
PLACE_TRADES = True

# Resolution
RESOLUTION = "1HOUR"

# Stats Window
WINDOW = 21

# Thresholds - Opening
MAX_HALF_LIFE = 24
ZSCORE_THRESH = 1.5
USD_PER_TRADE = 100
USD_MIN_COLLATERAL = 1880

# Thresholds - Closing
CLOSE_AT_ZSCORE_CROSS = True

# Ethereum Address
ETHEREUM_ADDRESS = "0xc01Cc7D52765e48EEc8DD2eA7A0Be16575aDD562"

# KEYS - PRODUCTION
# Must be on Mainnet in DYDX
STARK_PRIVATE_KEY_MAINNET = config("STARK_PRIVATE_KEY_MAINNET")
DYDX_API_KEY_MAINNET = config("217b310a-2483-6b0c-67a2-3afb4f492201")
DYDX_API_SECRET_MAINNET = config("DYDX_API_SECRET_MAINNET")
DYDX_API_PASSPHRASE_MAINNET = config("DYDX_API_PASSPHRASE_MAINNET")

# KEYS - DEVELOPMENT
# Must be on Testnet in DYDX
STARK_PRIVATE_KEY_TESTNET = config("06b651e3d32e29ad0fdc9fb84c49a60c057269dca055a3a22bd145a52d5543dc")
DYDX_API_KEY_TESTNET = config("217b310a-2483-6b0c-67a2-3afb4f492201")
DYDX_API_SECRET_TESTNET =config("QXUPcelO0JKQhL8DaRONyvYXtAPWRAlkQCtOZZIL")
DYDX_API_PASSPHRASE_TESTNET = config("q6h15sweCim_axsSW300")

# KEYS - Export
STARK_PRIVATE_KEY = STARK_PRIVATE_KEY_MAINNET if MODE == "PRODUCTION" else STARK_PRIVATE_KEY_TESTNET
DYDX_API_KEY = DYDX_API_KEY_MAINNET if MODE == "PRODUCTION" else DYDX_API_KEY_TESTNET
DYDX_API_SECRET = DYDX_API_SECRET_MAINNET if MODE == "PRODUCTION" else DYDX_API_SECRET_TESTNET
DYDX_API_PASSPHRASE = DYDX_API_PASSPHRASE_MAINNET if MODE == "PRODUCTION" else DYDX_API_PASSPHRASE_TESTNET

# HOST - Export
HOST = API_HOST_MAINNET if MODE == "PRODUCTION" else API_HOST_SEPOLIA

# HTTP PROVIDER
HTTP_PROVIDER_MAINNET = "https://eth-mainnet.g.alchemy.com/v2/2y4vjAW_JELsV0ZrFUg2NOoWklYtGLPS"
HTTP_PROVIDER_TESTNET = "https://eth-sepolia.g.alchemy.com/v2/WE99Q4PDmssAhfIuy5mcnbN31THKtRDg"
HTTP_PROVIDER = HTTP_PROVIDER_MAINNET if MODE == "PRODUCTION" else HTTP_PROVIDER_TESTNET